apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "junos_exporter.fullname" . }}
  labels:
    {{- include "junos_exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "junos_exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "junos_exporter.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "junos_exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9326
              protocol: TCP
          env:
          {{- if .Values.sshkey }}
          - name: SSH_KEYFILE
            value: "/ssh/ssh-keyfile"
          {{- end }}
          - name: CONFIG_FILE
            value: "/config/config.yml"
          {{- with .Values.extraEnv }}
          {{- toYaml . | trim | nindent 10 }}
          {{- end }}
          volumeMounts:
          - mountPath: /config
            name: {{ .Release.Name }}-configmap
          {{- if .Values.sshkey }}
          - mountPath: /ssh
            name: {{ .Release.Name }}-sshkey
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
